version: '3.8'

services:
  demo:
    container_name: demo-app
    build:
      context: .
      dockerfile: Dockerfile
    image: demo:local
    env_file:
      - .env.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app           # Mount local code into container (optional, for live reload)
    restart: unless-stopped
    command: npm run dev  # Or whatever your dev command is
